[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "click>=8.0",
    "flask>=3.0",
    "itsdangerous>=2.1",
    "jinja2>=3.1",
    "markupsafe>=2.1",
    "pytest>=9.0.2",
    "werkzeug>=3.0",
]
