services:
  lab1:
    build: ./1
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - URL_PREFIX=/labs/1
    networks:
      - web

  lab2:
    build: ./2
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - URL_PREFIX=/labs/2
    networks:
      - web

networks:
  web:
    external: true